version: '3.1'
services:
  mysql:
    container_name: realty
    image: 'mysql:8.0'
    working_dir: /application
    volumes:
      - '.:/application'
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=realty
      - MYSQL_USER=laravel
      - MYSQL_PASSWORD=password
    ports:
      - '3307:3306'
